### ISSUE TITLE
Fix tests when OTP is in 26 version or above

### ISSUE THREAD

**Issue by phcurado** [phcurado/daisy_ui_components#14]
Fix tests when OTP is in 26 or above version. The issue is shown under the tests on [this PR](https://github.com/phcurado/daisy_ui_components/pull/10). The attribute ordering changed after upgrading the OTP which made some tests break.

**Comment by brewerx** [comment]
This should be fixed now that this is merged 💪 https://github.com/phcurado/daisy_ui_components/pull/30

**Comment by phcurado** [comment]
thank you 💪
